---
# RedHat tasks file for ansible-role-logstash

- name: "Import Elastic's RPM Key"
  rpm_key:
    state: present
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: "Add Elastic Repository file"
  yum_repository:
    name: elastic
    description: Elastic repository for 9.x packages
    file: elastic
    baseurl: https://artifacts.elastic.co/packages/9.x/yum
    gpgcheck: true
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    enabled: true

- name: "Install the Logstash package (yum)"
  yum:
    name: "logstash"
    state: present
  register: install
  when:
    - ansible_facts['pkg_mgr'] == 'yum'

- name: "Install the Logstash package (dnf)"
  dnf:
    name: "logstash"
    state: present
  register: install
  when:
    - ansible_facts['pkg_mgr'] == 'dnf'

- name: "Reboot after Install"
  reboot:
    reboot_timeout: 3600
  when:
    - install.changed
